"""update_models_to_new_structure

Revision ID: 3da544da6072
Revises: d5b952df0df8
Create Date: 2025-05-19 14:55:01.232653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da544da6072'
down_revision: Union[str, None] = 'd5b952df0df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_review_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('pros_summary', sa.Text(), nullable=True),
    sa.Column('cons_summary', sa.Text(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id')
    )
    op.create_index(op.f('ix_tool_review_summaries_id'), 'tool_review_summaries', ['id'], unique=False)
    op.create_table('comparison_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_tools_id'), 'comparison_tools', ['id'], unique=False)
    op.drop_table('comparison_tool')
    op.alter_column('blog_comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('blog_comments_post_id_fkey', 'blog_comments', type_='foreignkey')
    op.drop_constraint('blog_comments_user_id_fkey', 'blog_comments', type_='foreignkey')
    op.drop_constraint('blog_comments_parent_id_fkey', 'blog_comments', type_='foreignkey')
    op.create_foreign_key(None, 'blog_comments', 'blog_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_comments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'blog_comments', 'blog_comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('blog_post_categories_post_id_fkey', 'blog_post_categories', type_='foreignkey')
    op.drop_constraint('blog_post_categories_category_id_fkey', 'blog_post_categories', type_='foreignkey')
    op.create_foreign_key(None, 'blog_post_categories', 'blog_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_post_categories', 'blog_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('blog_post_tags_post_id_fkey', 'blog_post_tags', type_='foreignkey')
    op.drop_constraint('blog_post_tags_tag_id_fkey', 'blog_post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'blog_post_tags', 'blog_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_post_tags', 'blog_tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('blog_posts_author_id_fkey', 'blog_posts', type_='foreignkey')
    op.create_foreign_key(None, 'blog_posts', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.add_column('categories', sa.Column('slug', sa.String(length=50), nullable=False))
    op.add_column('categories', sa.Column('icon', sa.String(length=100), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_constraint('comparisons_share_token_key', 'comparisons', type_='unique')
    op.create_index(op.f('ix_comparisons_share_token'), 'comparisons', ['share_token'], unique=True)
    op.drop_constraint('comparisons_user_id_fkey', 'comparisons', type_='foreignkey')
    op.create_foreign_key(None, 'comparisons', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('review_reactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review_reactions', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review_reactions', 'reaction_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint('unique_user_review_reaction', 'review_reactions', ['user_id', 'review_id'])
    op.drop_constraint('review_reactions_user_id_fkey', 'review_reactions', type_='foreignkey')
    op.drop_constraint('review_reactions_review_id_fkey', 'review_reactions', type_='foreignkey')
    op.create_foreign_key(None, 'review_reactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review_reactions', 'tool_reviews', ['review_id'], ['id'], ondelete='CASCADE')
    op.add_column('tags', sa.Column('slug', sa.String(length=50), nullable=False))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.add_column('technologies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('technologies', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('technologies', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('tool_category_tool_id_fkey', 'tool_category', type_='foreignkey')
    op.drop_constraint('tool_category_category_id_fkey', 'tool_category', type_='foreignkey')
    op.create_foreign_key(None, 'tool_category', 'tools', ['tool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tool_category', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tool_reviews', 'tool_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tool_reviews', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint('tool_reviews_tool_id_fkey', 'tool_reviews', type_='foreignkey')
    op.drop_constraint('tool_reviews_user_id_fkey', 'tool_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'tool_reviews', 'tools', ['tool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tool_reviews', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('tool_tag_tool_id_fkey', 'tool_tag', type_='foreignkey')
    op.drop_constraint('tool_tag_tag_id_fkey', 'tool_tag', type_='foreignkey')
    op.create_foreign_key(None, 'tool_tag', 'tools', ['tool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tool_tag', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tool_technology_tool_id_fkey', 'tool_technology', type_='foreignkey')
    op.drop_constraint('tool_technology_technology_id_fkey', 'tool_technology', type_='foreignkey')
    op.create_foreign_key(None, 'tool_technology', 'tools', ['tool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tool_technology', 'technologies', ['technology_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tools', 'slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_column('users', 'last_login')
    op.alter_column('tools', 'slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'tool_technology', type_='foreignkey')
    op.drop_constraint(None, 'tool_technology', type_='foreignkey')
    op.create_foreign_key('tool_technology_technology_id_fkey', 'tool_technology', 'technologies', ['technology_id'], ['id'])
    op.create_foreign_key('tool_technology_tool_id_fkey', 'tool_technology', 'tools', ['tool_id'], ['id'])
    op.drop_constraint(None, 'tool_tag', type_='foreignkey')
    op.drop_constraint(None, 'tool_tag', type_='foreignkey')
    op.create_foreign_key('tool_tag_tag_id_fkey', 'tool_tag', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('tool_tag_tool_id_fkey', 'tool_tag', 'tools', ['tool_id'], ['id'])
    op.drop_constraint(None, 'tool_reviews', type_='foreignkey')
    op.drop_constraint(None, 'tool_reviews', type_='foreignkey')
    op.create_foreign_key('tool_reviews_user_id_fkey', 'tool_reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key('tool_reviews_tool_id_fkey', 'tool_reviews', 'tools', ['tool_id'], ['id'])
    op.alter_column('tool_reviews', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tool_reviews', 'tool_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'tool_category', type_='foreignkey')
    op.drop_constraint(None, 'tool_category', type_='foreignkey')
    op.create_foreign_key('tool_category_category_id_fkey', 'tool_category', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('tool_category_tool_id_fkey', 'tool_category', 'tools', ['tool_id'], ['id'])
    op.alter_column('technologies', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('technologies', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('technologies', 'updated_at')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'slug')
    op.drop_constraint(None, 'review_reactions', type_='foreignkey')
    op.drop_constraint(None, 'review_reactions', type_='foreignkey')
    op.create_foreign_key('review_reactions_review_id_fkey', 'review_reactions', 'tool_reviews', ['review_id'], ['id'])
    op.create_foreign_key('review_reactions_user_id_fkey', 'review_reactions', 'users', ['user_id'], ['id'])
    op.drop_constraint('unique_user_review_reaction', 'review_reactions', type_='unique')
    op.alter_column('review_reactions', 'reaction_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('review_reactions', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review_reactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'comparisons', type_='foreignkey')
    op.create_foreign_key('comparisons_user_id_fkey', 'comparisons', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_comparisons_share_token'), table_name='comparisons')
    op.create_unique_constraint('comparisons_share_token_key', 'comparisons', ['share_token'])
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.alter_column('categories', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'icon')
    op.drop_column('categories', 'slug')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.create_foreign_key('blog_posts_author_id_fkey', 'blog_posts', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'blog_post_tags', type_='foreignkey')
    op.drop_constraint(None, 'blog_post_tags', type_='foreignkey')
    op.create_foreign_key('blog_post_tags_tag_id_fkey', 'blog_post_tags', 'blog_tags', ['tag_id'], ['id'])
    op.create_foreign_key('blog_post_tags_post_id_fkey', 'blog_post_tags', 'blog_posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'blog_post_categories', type_='foreignkey')
    op.drop_constraint(None, 'blog_post_categories', type_='foreignkey')
    op.create_foreign_key('blog_post_categories_category_id_fkey', 'blog_post_categories', 'blog_categories', ['category_id'], ['id'])
    op.create_foreign_key('blog_post_categories_post_id_fkey', 'blog_post_categories', 'blog_posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'blog_comments', type_='foreignkey')
    op.drop_constraint(None, 'blog_comments', type_='foreignkey')
    op.drop_constraint(None, 'blog_comments', type_='foreignkey')
    op.create_foreign_key('blog_comments_parent_id_fkey', 'blog_comments', 'blog_comments', ['parent_id'], ['id'])
    op.create_foreign_key('blog_comments_user_id_fkey', 'blog_comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key('blog_comments_post_id_fkey', 'blog_comments', 'blog_posts', ['post_id'], ['id'])
    op.alter_column('blog_comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('comparison_tool',
    sa.Column('comparison_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tool_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], name='comparison_tool_comparison_id_fkey'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name='comparison_tool_tool_id_fkey'),
    sa.PrimaryKeyConstraint('comparison_id', 'tool_id', name='comparison_tool_pkey')
    )
    op.drop_index(op.f('ix_comparison_tools_id'), table_name='comparison_tools')
    op.drop_table('comparison_tools')
    op.drop_index(op.f('ix_tool_review_summaries_id'), table_name='tool_review_summaries')
    op.drop_table('tool_review_summaries')
    # ### end Alembic commands ###
