# Generated by Django 5.2 on 2025-04-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'کاربر عادی'), ('admin', 'مدیر سایت')], default='user', max_length=10),
        ),
    ]
