# Generated by Django 5.2 on 2025-05-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='phone',
            new_name='mobile',
        ),
    ]
