# Generated by Django 5.2 on 2025-04-14 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('license_type', models.CharField(choices=[('free', 'رایگان'), ('paid', 'پولی'), ('freemium', 'فریمیوم')], max_length=10)),
                ('supports_farsi', models.BooleanField(default=False)),
                ('is_sanctioned', models.BooleanField(default=False)),
                ('is_filtered', models.BooleanField(default=False)),
                ('highlight_feature', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('homepage_screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_chatbot', models.BooleanField(default=False)),
                ('multi_language_support', models.BooleanField(default=False)),
                ('desktop_version', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='tools.category')),
                ('technologies', models.ManyToManyField(to='tools.technology')),
            ],
        ),
        migrations.CreateModel(
            name='ToolReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tools.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
