# Generated by Django 5.2 on 2025-04-20 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tag_tool_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolreview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tools.toolreview', verbose_name='پاسخ به نظر'),
        ),
    ]
