# Generated by Django 5.2 on 2025-04-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_toolreview_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
